//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAPI.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 类别名称不能为空 的本地化字符串。
        /// </summary>
        public static string apidata_category_valid_empty {
            get {
                return ResourceManager.GetString("apidata_category_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别名称不能大于40位 的本地化字符串。
        /// </summary>
        public static string apidata_category_valid_len {
            get {
                return ResourceManager.GetString("apidata_category_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空 的本地化字符串。
        /// </summary>
        public static string apidata_name_valid_empty {
            get {
                return ResourceManager.GetString("apidata_name_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称的长度不能大于40 的本地化字符串。
        /// </summary>
        public static string apidata_name_valid_len {
            get {
                return ResourceManager.GetString("apidata_name_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父ID不能为空，最顶级请用0 的本地化字符串。
        /// </summary>
        public static string apidata_parentid_valid_empty {
            get {
                return ResourceManager.GetString("apidata_parentid_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品ID不能为空 的本地化字符串。
        /// </summary>
        public static string apidata_productid_valid_empty {
            get {
                return ResourceManager.GetString("apidata_productid_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号不能为空 的本地化字符串。
        /// </summary>
        public static string apidata_serialnumber_valid_empty {
            get {
                return ResourceManager.GetString("apidata_serialnumber_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认中文 的本地化字符串。
        /// </summary>
        public static string culture {
            get {
                return ResourceManager.GetString("culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者邮箱不正确 的本地化字符串。
        /// </summary>
        public static string cusomerinfo_devemail_valid_empty {
            get {
                return ResourceManager.GetString("cusomerinfo_devemail_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发者邮箱不能大于128 的本地化字符串。
        /// </summary>
        public static string cusomerinfo_devemail_valid_len {
            get {
                return ResourceManager.GetString("cusomerinfo_devemail_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售邮箱格式不正确 的本地化字符串。
        /// </summary>
        public static string cusomerinfo_salespersonemail_valid_empty {
            get {
                return ResourceManager.GetString("cusomerinfo_salespersonemail_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售Email不能大于128 的本地化字符串。
        /// </summary>
        public static string cusomerinfo_salespersonemail_valid_len {
            get {
                return ResourceManager.GetString("cusomerinfo_salespersonemail_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nss营业邮箱不能为空 的本地化字符串。
        /// </summary>
        public static string customerinfo_nssemail_valid_empty {
            get {
                return ResourceManager.GetString("customerinfo_nssemail_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nss营业邮箱格式不正确 的本地化字符串。
        /// </summary>
        public static string customerinfo_nssemail_valid_format {
            get {
                return ResourceManager.GetString("customerinfo_nssemail_valid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 nss营业邮箱长度不能超过120 的本地化字符串。
        /// </summary>
        public static string customerinfo_nssemail_valid_len {
            get {
                return ResourceManager.GetString("customerinfo_nssemail_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用场景不能为空 的本地化字符串。
        /// </summary>
        public static string customerinfo_scene_valid_empty {
            get {
                return ResourceManager.GetString("customerinfo_scene_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称不能为空 的本地化字符串。
        /// </summary>
        public static string customint_companname_valid_empty {
            get {
                return ResourceManager.GetString("customint_companname_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称不能超过250位 的本地化字符串。
        /// </summary>
        public static string customint_companname_valid_len {
            get {
                return ResourceManager.GetString("customint_companname_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 担当Email不能为空 的本地化字符串。
        /// </summary>
        public static string customint_responsibleemail_valid_empty {
            get {
                return ResourceManager.GetString("customint_responsibleemail_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 担当者邮箱格式不正确 的本地化字符串。
        /// </summary>
        public static string customint_responsibleemail_valid_format {
            get {
                return ResourceManager.GetString("customint_responsibleemail_valid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 担当Email不能大于120 的本地化字符串。
        /// </summary>
        public static string customint_responsibleemail_valid_len {
            get {
                return ResourceManager.GetString("customint_responsibleemail_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 营业担当不能为空 的本地化字符串。
        /// </summary>
        public static string customint_responsibleperson_valid_empty {
            get {
                return ResourceManager.GetString("customint_responsibleperson_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 营业担当不能大于120 的本地化字符串。
        /// </summary>
        public static string customint_responsibleperson_valid_len {
            get {
                return ResourceManager.GetString("customint_responsibleperson_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称不能为空 的本地化字符串。
        /// </summary>
        public static string product_name_valid_empty {
            get {
                return ResourceManager.GetString("product_name_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称不能超过40 的本地化字符串。
        /// </summary>
        public static string product_name_valid_len {
            get {
                return ResourceManager.GetString("product_name_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景ID不能为空 的本地化字符串。
        /// </summary>
        public static string product_sceneid_valid_empty {
            get {
                return ResourceManager.GetString("product_sceneid_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号不能为空 的本地化字符串。
        /// </summary>
        public static string product_version_valid_empty {
            get {
                return ResourceManager.GetString("product_version_valid_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号长度不能超过40 的本地化字符串。
        /// </summary>
        public static string product_version_valid_len {
            get {
                return ResourceManager.GetString("product_version_valid_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始全流程构建…… 的本地化字符串。
        /// </summary>
        public static string run_00 {
            get {
                return ResourceManager.GetString("run_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始代码上传…… 的本地化字符串。
        /// </summary>
        public static string run_01 {
            get {
                return ResourceManager.GetString("run_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码上传成功！ 的本地化字符串。
        /// </summary>
        public static string run_02 {
            get {
                return ResourceManager.GetString("run_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始部署代码，请给我一点时间…… 的本地化字符串。
        /// </summary>
        public static string run_03 {
            get {
                return ResourceManager.GetString("run_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建函数{0}成功！ 的本地化字符串。
        /// </summary>
        public static string run_04 {
            get {
                return ResourceManager.GetString("run_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始启动服务…… 的本地化字符串。
        /// </summary>
        public static string run_05 {
            get {
                return ResourceManager.GetString("run_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动服务{0}成功！ 的本地化字符串。
        /// </summary>
        public static string run_06 {
            get {
                return ResourceManager.GetString("run_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始访问服务…… 的本地化字符串。
        /// </summary>
        public static string run_07 {
            get {
                return ResourceManager.GetString("run_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问服务{0}成功 的本地化字符串。
        /// </summary>
        public static string run_08 {
            get {
                return ResourceManager.GetString("run_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务返回数据： 的本地化字符串。
        /// </summary>
        public static string run_09 {
            get {
                return ResourceManager.GetString("run_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束全流程构建！ 的本地化字符串。
        /// </summary>
        public static string run_99 {
            get {
                return ResourceManager.GetString("run_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码上传失败！ 的本地化字符串。
        /// </summary>
        public static string run_err_01 {
            get {
                return ResourceManager.GetString("run_err_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建函数{0}失败！ 的本地化字符串。
        /// </summary>
        public static string run_err_02 {
            get {
                return ResourceManager.GetString("run_err_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置函数{0}权限失败！ 的本地化字符串。
        /// </summary>
        public static string run_err_03 {
            get {
                return ResourceManager.GetString("run_err_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问服务{0}失败！ 的本地化字符串。
        /// </summary>
        public static string run_err_04 {
            get {
                return ResourceManager.GetString("run_err_04", resourceCulture);
            }
        }
    }
}
